version: '3'

services:
###> doctrine/doctrine-bundle ###
###  database:
###    ports:
###      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< symfony/mailer ###

  php:
    container_name: php
    build:
      context: ./docker/php
###    ports:
###      - '9000:9000'
    volumes:
      - .:/var/www/calendars
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '127.0.0.1:8080:80'
    volumes:
      - .:/var/www/calendars
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database